name: ci

on: push

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          
      - name: Format code
        run: go fmt .

      - name: Unit tests
        run: go test .
